### ISSUE TITLE
npm ERR! code ERESOLVE npm ERR! ERESOLVE could not resolve

### ISSUE THREAD

**Issue by spaceinvadev** [apollographql/odyssey-lift-off-part1#19]
I came across the following error when attempting to install `@apollo/client` by following the instructions from chapter [8. Apollo Client Setup](https://odyssey.apollographql.com/lift-off-part1/apollo-client-setup) of the LIFT-OFF I: BASICS course.

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: catstronauts-client@1.0.0
npm ERR! Found: graphql@14.7.0
npm ERR! node_modules/graphql
npm ERR!   peer graphql@"^14.5.0 || ^15.0.0" from @apollo/federation@0.27.0
...
```

<img width="1044" alt="Screen Shot 2021-11-15 at 5 27 55 PM" src="https://user-images.githubusercontent.com/49292621/141862887-a37532f7-990b-4dea-83e7-a1518dfbd07c.png">

Here's the complete log file
[2021-11-15T22_17_09_725Z-debug.log](https://github.com/apollographql/odyssey-lift-off-part1/files/7542004/2021-11-15T22_17_09_725Z-debug.log)
:

**Comment by mabuyo** [comment]
Hi @spaceinvadev! Can you try running the installs separately? So run `npm install graphql` first, then when that's done, run `npm install @apollo/client`? 

I think this may be [the same issue another person was experiencing](https://community.apollographql.com/t/lift-off-1-apollo-client-setup/1961).

PS: for future issues, please [post in the community forums](https://community.apollographql.com/tag/odyssey)! We can keep troubleshooting here, but for next time :) Thank you!

**Comment by spaceinvadev** [comment]
Thanks, @mabuyo.

Running the scripts separately prevented me from having the error.
