### ISSUE TITLE
Cross-Origin Request Blocked at useQuery Step

### ISSUE THREAD

**Issue by ericsun95** [apollographql/odyssey-lift-off-part1#21]
Meet the following Issue: 
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://localhost:4000/. (Reason: CORS request did not succeed). Status code: (null).
```
When following the guidance https://odyssey.apollographql.com/lift-off-part1/the-usequery-hook to use `useQuery` to fetch data in the client.

Any clues?

**Comment by mabuyo** [comment]
Hi @ericsun95! Apologies for the extremely late reply, we don't actively monitor this repo!

If you haven't resolved this issue yet and want to give it a try, the first thing I would try is changing the URL from `https` to `http` (no s). 

Another thing that would help to troubleshoot is if you could send us a link to your code so we can try and duplicate the problem!

Thanks so much for reaching out! For any further troubleshooting, could you please [post in our community forum](https://community.apollographql.com/tag/odyssey) in the Odyssey tag? We'll help you out there.

Have a great day!
