### ISSUE TITLE
Error starting client

### ISSUE THREAD

**Issue by AndrewKeig** [apollographql/odyssey-lift-off-part1#4]
Issue:  Error starting client

```
final/client/src/pages/__generated__/login"' has no exported member 'loginVariables'.
```

Solution

interface is exporting LoginTypes.LoginVariables not LoginTypes.loginVariables

**Comment by mabuyo** [comment]
Hi @AndrewKeig! I can't seem to find the page or variable you're referring to. Can you clarify the steps you're talking that are leading you to this error?

**Comment by AndrewKeig** [comment]
Apologies wrong repo.
